<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHW9Yiac\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHW9Yiac/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHW9Yiac.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHW9Yiac\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHW9Yiac\App_KernelDevDebugContainer([
    'container.build_hash' => 'HW9Yiac',
    'container.build_id' => 'aa7ab8b7',
    'container.build_time' => 1739490276,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHW9Yiac');
