<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWk6hbIC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWk6hbIC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWk6hbIC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWk6hbIC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWk6hbIC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wk6hbIC',
    'container.build_id' => 'a8cc8d1f',
    'container.build_time' => 1739486183,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWk6hbIC');
